version: '3.11'


services:
  db:
    image: nouchka/sqlite3:latest
    environment:
      - SQLITE3_DB=db.sqlite3
    expose:
      - 5432
    ports:
      - 5432:5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python3 /app/manage.py collectstatic --noinput --clear && gunicorn task.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web
